compile-server:
	g++ server.cpp server_functions.hpp -o server -lpthread

compile-client:
	g++ client.cpp -o client

compile-admin:
	g++ admin.cpp -o admin

compile-all:
	g++ server.cpp server_functions.hpp -o server -lpthread
	g++ client.cpp -o client
	g++ admin.cpp -o admin
